version: '2'

services:
  example-db:
    container_name: example-db
    image: mariadb:latest
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=examplerootpassword
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=examplepassword
    restart: always

  db-backup:
    container_name: db-backup
    image: brouzuf/mariadbbackup
    links:
     - example-db
    volumes:
      - ./backups:/backups
    environment:
      - DB_SERVER=example-db
      - DB_NAME=example
      - DB_USER=root
      - DB_PASSWORD="examplepassword"
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0305
      - DB_CLEANUP_TIME=40320
      - MD5=TRUE
      - COMPRESSION=XZ
      - SPLIT_DB=TRUE

    restart: always


